parameters:
    # URL alias router used for overriding URL alias view action
    netgen_ez_platform_site_api.urlalias_router.class: Netgen\Bundle\EzPlatformSiteApiBundle\Routing\UrlAliasRouter

    # Preview controller used for overriding URL alias view action
    netgen_ez_platform_site_api.preview_controller.class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\PreviewController

    # Template defaults for standard eZ Platform installation
    # By default we don't override URL alias view action, for that reason these are commented out
    #ezplatform.default_view_templates.content.full: 'NetgenEzPlatformSiteApiBundle:default:content/full.html.twig'
    #ezsettings.default.pagelayout: 'NetgenEzPlatformSiteApiBundle::pagelayout.html.twig'

    # Defaults for semantic configuration
    netgen_ez_platform_site_api.default.override_url_alias_view_action: false
    netgen_ez_platform_site_api.default.use_always_available_fallback: true

services:
    netgen.ezplatform_site.controller.base:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\Controller
        abstract: true
        calls:
            - [setContainer, ['@service_container']]
            - [setSite, ['@netgen.ezplatform_site.core.site']]

    netgen.ezplatform_site.core.settings:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Core\Site\Settings
        arguments:
            - '@ezpublish.config.resolver'

    netgen.ezplatform_site.controller.content.view:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\Content\ViewController
        parent: ezpublish.controller.base

    ng_content:
        alias: netgen.ezplatform_site.controller.content.view

    netgen.ezplatform_site.twig.extension.field_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\FieldRenderingExtension
        tags:
            - {name: twig.extension}

    netgen.ezplatform_site.twig.runtime.field_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\FieldRenderingRuntime
        # public: false
        arguments:
            - '@twig'
            - '@ezpublish.templating.field_block_renderer'
            - '@ezpublish.fieldType.parameterProviderRegistry'
        tags:
            - {name: twig.runtime}

    netgen.ezplatform_site.twig.extension.image:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ImageExtension
        tags:
            - {name: twig.extension}

    netgen.ezplatform_site.twig.runtime.image:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ImageRuntime
        # public: false
        arguments:
            - '@ezpublish.fieldType.ezimage.variation_service'
        tags:
            - {name: twig.runtime}

    netgen.ezplatform_site.twig.runtime_loader:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\RuntimeLoader
        public: false
        arguments:
            - ['@netgen.ezplatform_site.twig.runtime.field_rendering', '@netgen.ezplatform_site.twig.runtime.image']
